[pytest]
testpaths = tests
python_files = test_*.py

filterwarnings =
    ignore:The anyio.abc.BlockingPortal alias is deprecated:DeprecationWarning
    ignore:.*oneOf.*deprecated.*:DeprecationWarning
    ignore:.*parseString.*deprecated.*:DeprecationWarning
    ignore:.*resetCache.*deprecated.*:DeprecationWarning
    ignore:.*enablePackrat.*deprecated.*:DeprecationWarning